apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma-web
spec:
  template:
    spec:
      containers:
        - name: web
          image: ghcr.io/personal-pm/web:latest
          ports: [{containerPort: 3000}]
