"""planning core schema

Revision ID: 208d77790940
Revises:
Create Date: 2026-08-23 14:12:58.654975
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None  # initial schema
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "workspaces",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_workspaces_owner_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspaces")),
    )
    op.create_index(
        op.f("ix_workspaces_owner_user_id"), "workspaces", ["owner_user_id"], unique=False
    )
    op.create_table(
        "areas",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_areas_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_areas")),
    )
    op.create_index(op.f("ix_areas_workspace_id"), "areas", ["workspace_id"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("entity_kind", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=False),
        sa.Column("before_state", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after_state", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("rule_basis", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("approval_id", sa.Uuid(), nullable=True),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("reversible", sa.Boolean(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_events_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_audit_events_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(
        op.f("ix_audit_events_workspace_id"), "audit_events", ["workspace_id"], unique=False
    )
    op.create_table(
        "availability_windows",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tags_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "end_at > start_at", name=op.f("ck_availability_windows_positive_window")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_availability_windows_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_availability_windows")),
    )
    op.create_index(
        op.f("ix_availability_windows_workspace_id"),
        "availability_windows",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "calendar_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("external_calendar_id", sa.String(length=200), nullable=False),
        sa.Column("external_event_id", sa.String(length=200), nullable=False),
        sa.Column("external_version", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("event_kind", sa.String(length=25), nullable=False),
        sa.Column("deadline_date", sa.Date(), nullable=True),
        sa.Column("sync_status", sa.String(length=25), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("end_at > start_at", name=op.f("ck_calendar_events_positive_window")),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_calendar_events_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calendar_events")),
    )
    op.create_index(
        op.f("ix_calendar_events_workspace_id"), "calendar_events", ["workspace_id"], unique=False
    )
    op.create_index(
        "uq_calendar_events_active_provider_identity",
        "calendar_events",
        ["external_calendar_id", "external_event_id"],
        unique=True,
        postgresql_where=sa.text("sync_status <> 'tombstoned'"),
    )
    op.create_table(
        "outbox_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("operation_id", sa.Uuid(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=120), nullable=False),
        sa.Column("command_type", sa.String(length=60), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=25), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_outbox_events_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_events")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_outbox_events_idempotency_key")),
    )
    op.create_index(
        "ix_outbox_events_pending_delivery", "outbox_events", ["status", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_outbox_events_workspace_id"), "outbox_events", ["workspace_id"], unique=False
    )
    op.create_table(
        "plan_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("planner_version", sa.String(length=40), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("output_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_plan_snapshots_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan_snapshots")),
    )
    op.create_index(
        op.f("ix_plan_snapshots_workspace_id"), "plan_snapshots", ["workspace_id"], unique=False
    )
    op.create_index(
        "uq_plan_snapshots_one_current_per_workspace",
        "plan_snapshots",
        ["workspace_id"],
        unique=True,
        postgresql_where=sa.text("is_current IS true"),
    )
    op.create_table(
        "external_executions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("outbox_event_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=120), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=True),
        sa.Column("result_status", sa.String(length=30), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "verified = false OR external_id IS NOT NULL",
            name=op.f("ck_external_executions_verified_has_external_id"),
        ),
        sa.ForeignKeyConstraint(
            ["outbox_event_id"],
            ["outbox_events.id"],
            name=op.f("fk_external_executions_outbox_event_id_outbox_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_executions")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_external_executions_idempotency_key")),
    )
    op.create_index(
        "ix_external_executions_outbox_unique",
        "external_executions",
        ["outbox_event_id"],
        unique=True,
    )
    op.create_table(
        "workstreams",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("area_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("importance", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["area_id"],
            ["areas.id"],
            name=op.f("fk_workstreams_area_id_areas"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_workstreams_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workstreams")),
    )
    op.create_index(
        op.f("ix_workstreams_workspace_id"), "workstreams", ["workspace_id"], unique=False
    )
    op.create_table(
        "milestones",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("workstream_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("deadline_date", sa.Date(), nullable=True),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deadline_date_known", sa.Boolean(), nullable=False),
        sa.Column("deadline_time_known", sa.Boolean(), nullable=False),
        sa.Column("deadline_type", sa.String(length=30), nullable=False),
        sa.Column("required_buffer_minutes", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(deadline_time_known = false) OR (deadline_at IS NOT NULL)",
            name=op.f("ck_milestones_known_time_requires_instant"),
        ),
        sa.CheckConstraint(
            "(deadline_time_known = true) OR (deadline_at IS NULL)",
            name=op.f("ck_milestones_unknown_time_forbids_instant"),
        ),
        sa.CheckConstraint(
            "required_buffer_minutes >= 0", name=op.f("ck_milestones_buffer_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_milestones_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workstream_id"],
            ["workstreams.id"],
            name=op.f("fk_milestones_workstream_id_workstreams"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_milestones")),
    )
    op.create_index(
        op.f("ix_milestones_workspace_id"), "milestones", ["workspace_id"], unique=False
    )
    op.create_index(
        op.f("ix_milestones_workstream_id"), "milestones", ["workstream_id"], unique=False
    )
    op.create_table(
        "proposals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=60), nullable=False),
        sa.Column("approval_level", sa.String(length=20), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("targets_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("milestone_id", sa.Uuid(), nullable=True),
        sa.Column("minutes_saved_or_added", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["milestone_id"],
            ["milestones.id"],
            name=op.f("fk_proposals_milestone_id_milestones"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_proposals_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proposals")),
    )
    op.create_index(op.f("ix_proposals_workspace_id"), "proposals", ["workspace_id"], unique=False)
    op.create_table(
        "tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("workstream_id", sa.Uuid(), nullable=False),
        sa.Column("milestone_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("deadline_date", sa.Date(), nullable=True),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deadline_time_known", sa.Boolean(), nullable=False),
        sa.Column("start_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("base_duration_minutes", sa.Integer(), nullable=False),
        sa.Column("safety_duration_minutes", sa.Integer(), nullable=False),
        sa.Column("remaining_base_minutes", sa.Integer(), nullable=False),
        sa.Column("remaining_safety_minutes", sa.Integer(), nullable=False),
        sa.Column("uncertainty", sa.String(length=10), nullable=False),
        sa.Column("splittable", sa.Boolean(), nullable=False),
        sa.Column("min_chunk_minutes", sa.Integer(), nullable=False),
        sa.Column("pinned", sa.Boolean(), nullable=False),
        sa.Column("waiting_reason", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status NOT IN ('done','cancelled')) OR "
            "(remaining_base_minutes = 0 AND remaining_safety_minutes = 0)",
            name=op.f("ck_tasks_terminal_has_no_remaining"),
        ),
        sa.CheckConstraint(
            "(deadline_time_known = false) OR (deadline_at IS NOT NULL)",
            name=op.f("ck_tasks_known_time_requires_instant"),
        ),
        sa.CheckConstraint("base_duration_minutes > 0", name=op.f("ck_tasks_base_positive")),
        sa.CheckConstraint("min_chunk_minutes > 0", name=op.f("ck_tasks_chunk_positive")),
        sa.CheckConstraint(
            "safety_duration_minutes >= base_duration_minutes",
            name=op.f("ck_tasks_safety_gte_base"),
        ),
        sa.ForeignKeyConstraint(
            ["milestone_id"],
            ["milestones.id"],
            name=op.f("fk_tasks_milestone_id_milestones"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_tasks_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workstream_id"],
            ["workstreams.id"],
            name=op.f("fk_tasks_workstream_id_workstreams"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
    )
    op.create_index(op.f("ix_tasks_workspace_id"), "tasks", ["workspace_id"], unique=False)
    op.create_table(
        "approvals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("proposal_id", sa.Uuid(), nullable=False),
        sa.Column("proposal_version", sa.Integer(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=False),
        sa.Column("action_type", sa.String(length=40), nullable=False),
        sa.Column("command_hash", sa.String(length=64), nullable=False),
        sa.Column("targets_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["proposals.id"],
            name=op.f("fk_approvals_proposal_id_proposals"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_approvals_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
    )
    op.create_index(op.f("ix_approvals_workspace_id"), "approvals", ["workspace_id"], unique=False)
    op.create_table(
        "task_dependencies",
        sa.Column("predecessor_id", sa.Uuid(), nullable=False),
        sa.Column("successor_id", sa.Uuid(), nullable=False),
        sa.Column("dependency_type", sa.String(length=25), nullable=False),
        sa.CheckConstraint(
            "predecessor_id <> successor_id", name=op.f("ck_task_dependencies_no_self_dependency")
        ),
        sa.ForeignKeyConstraint(
            ["predecessor_id"],
            ["tasks.id"],
            name=op.f("fk_task_dependencies_predecessor_id_tasks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["successor_id"],
            ["tasks.id"],
            name=op.f("fk_task_dependencies_successor_id_tasks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "predecessor_id", "successor_id", "dependency_type", name=op.f("pk_task_dependencies")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task_dependencies")
    op.drop_index(op.f("ix_approvals_workspace_id"), table_name="approvals")
    op.drop_table("approvals")
    op.drop_index(op.f("ix_tasks_workspace_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_proposals_workspace_id"), table_name="proposals")
    op.drop_table("proposals")
    op.drop_index(op.f("ix_milestones_workstream_id"), table_name="milestones")
    op.drop_index(op.f("ix_milestones_workspace_id"), table_name="milestones")
    op.drop_table("milestones")
    op.drop_index(op.f("ix_workstreams_workspace_id"), table_name="workstreams")
    op.drop_table("workstreams")
    op.drop_index("ix_external_executions_outbox_unique", table_name="external_executions")
    op.drop_table("external_executions")
    op.drop_index(
        "uq_plan_snapshots_one_current_per_workspace",
        table_name="plan_snapshots",
        postgresql_where=sa.text("is_current IS true"),
    )
    op.drop_index(op.f("ix_plan_snapshots_workspace_id"), table_name="plan_snapshots")
    op.drop_table("plan_snapshots")
    op.drop_index(op.f("ix_outbox_events_workspace_id"), table_name="outbox_events")
    op.drop_index("ix_outbox_events_pending_delivery", table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_index(
        "uq_calendar_events_active_provider_identity",
        table_name="calendar_events",
        postgresql_where=sa.text("sync_status <> 'tombstoned'"),
    )
    op.drop_index(op.f("ix_calendar_events_workspace_id"), table_name="calendar_events")
    op.drop_table("calendar_events")
    op.drop_index(op.f("ix_availability_windows_workspace_id"), table_name="availability_windows")
    op.drop_table("availability_windows")
    op.drop_index(op.f("ix_audit_events_workspace_id"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_areas_workspace_id"), table_name="areas")
    op.drop_table("areas")
    op.drop_index(op.f("ix_workspaces_owner_user_id"), table_name="workspaces")
    op.drop_table("workspaces")
    op.drop_table("users")
    # ### end Alembic commands ###
