"""inbox items and candidates

Revision ID: 3b47b7d7d201
Revises: 0004
Create Date: 2026-08-26 01:57:09.690316
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbox_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('source_artifact_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("kind IN ('file','text','image')", name=op.f('ck_inbox_items_valid_kind')),
    sa.ForeignKeyConstraint(['source_artifact_id'], ['source_artifacts.id'], name=op.f('fk_inbox_items_source_artifact_id_source_artifacts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_inbox_items_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inbox_items'))
    )
    op.create_index(op.f('ix_inbox_items_workspace_id'), 'inbox_items', ['workspace_id'], unique=False)
    op.create_table('candidate_facts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inbox_item_id', sa.Uuid(), nullable=False),
    sa.Column('operation_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_score', sa.Float(), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inbox_item_id'], ['inbox_items.id'], name=op.f('fk_candidate_facts_inbox_item_id_inbox_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_facts'))
    )
    op.create_index(op.f('ix_candidate_facts_inbox_item_id'), 'candidate_facts', ['inbox_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_facts_inbox_item_id'), table_name='candidate_facts')
    op.drop_table('candidate_facts')
    op.drop_index(op.f('ix_inbox_items_workspace_id'), table_name='inbox_items')
    op.drop_table('inbox_items')
    # ### end Alembic commands ###
