"""external calendar events

Revision ID: 649cc41e99ab
Revises: 0005
Create Date: 2026-08-26 02:45:30.167438
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0006"
down_revision = "0005"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "external_calendar_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("external_event_id", sa.String(length=200), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("all_day", sa.Boolean(), nullable=False),
        sa.Column("blocks_capacity", sa.Boolean(), nullable=False),
        sa.Column("availability_type", sa.String(length=30), nullable=False),
        sa.Column("provider_status", sa.String(length=20), nullable=False),
        sa.Column("managed_focus_block", sa.Boolean(), nullable=False),
        sa.Column("pending_internal_reconciliation", sa.Boolean(), nullable=False),
        sa.Column("outbound_restore_requested", sa.Boolean(), nullable=False),
        sa.Column("sync_status", sa.String(length=25), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider_version", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_external_calendar_events_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_calendar_events")),
    )
    op.create_index(
        op.f("ix_external_calendar_events_workspace_id"),
        "external_calendar_events",
        ["workspace_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_external_calendar_events_workspace_id"), table_name="external_calendar_events"
    )
    op.drop_table("external_calendar_events")
    # ### end Alembic commands ###
