"""proposal versions

Revision ID: 52792ac4b8ff
Revises: 0006
Create Date: 2026-08-26 02:49:25.661128
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0007"
down_revision = "0006"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("proposals", sa.Column("version", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("proposals", "version")
    # ### end Alembic commands ###
