"""agent operations

Revision ID: 8853b7ac33a1
Revises: 0007
Create Date: 2026-08-26 03:11:29.311055
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0008"
down_revision = "0007"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_operations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("user_text", sa.String(length=2000), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_agent_operations_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_operations")),
    )
    op.create_index(
        op.f("ix_agent_operations_workspace_id"), "agent_operations", ["workspace_id"], unique=False
    )
    op.create_table(
        "operation_step_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("operation_id", sa.Uuid(), nullable=False),
        sa.Column("step", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "sequence >= 0", name=op.f("ck_operation_step_events_nonnegative_sequence")
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["agent_operations.id"],
            name=op.f("fk_operation_step_events_operation_id_agent_operations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operation_step_events")),
    )
    op.create_index(
        op.f("ix_operation_step_events_operation_id"),
        "operation_step_events",
        ["operation_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_operation_step_events_operation_id"), table_name="operation_step_events")
    op.drop_table("operation_step_events")
    op.drop_index(op.f("ix_agent_operations_workspace_id"), table_name="agent_operations")
    op.drop_table("agent_operations")
    # ### end Alembic commands ###
